url_templates/base_app/urls.py
from django.conf.urls import url,include

from base_app import views


app_name = 'base_app'

urlpatterns = [
    url('relative/',views.relative,name='relative'),
    url('others/',views.others,name='others'),
]

url_templates/url_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from base_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin',admin.site.urls),
    path('base_app',include('base_app.urls'))
]

url_templates/base_app/models.py
from django.db import models

# Create your models here.

url_templates/base_app/views.py
from django.shortcuts import render
from base_app import views
# Create your views here.
def index(request):
    return render(request,'base_app/index.html')

def others(request):
    return render(request,'base_app/others.html')

def relative(request):
    return render(request,'base_app/relative_turls.html')

url_templates/templates/base_app/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>level four</title>
  </head>
  <body>
    <h1>wwelcome to index</h1>
  </body>
</html>

url_templates/templates/base_app/others.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO OTHER</h1>
  </body>
</html>

url_templates/templates/base_app/relative_turls.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>the main page</title>
  </head>
  <body>
    <h1>welcome to turl homepage</h1>
    <a href="{% url 'base_app:others' %}">the others page</a>
    <a href="{% url 'admin:index' %}">link to admin</a>
    <a href="{% url 'index' %}">link to index</a>
  </body>
</html>